alias bi='bundle install'
alias be='bundle exec'
alias bers='bundle exec rails s -p'
alias gs="git status"
alias gk="git checkout"
alias gc="git commit -m"
alias gh="git push origin"
alias gl="git pull origin"
alias gm="git merge"
